### ISSUE TITLE
Can't find `dummy` in `struct disk_header`

### ISSUE THREAD

**Issue by madper** [agriel/Minimal-read-write-filesystem#3]
Hi Agriel, 
   Sorry for distrub. I just can't compile your code without commenting this line:   `((struct disk_header*)sb->s_fs_info)->dummy[100]=0;`
I'm not very sure what you really want to do in that line. could you please tell me? Also that I have checked that structure, it have no dummy inside. here is the define of the struct:
    http://lxr.linux.no/#linux+v3.8.3/drivers/md/dm-snap-persistent.c#L61

Thanks,
Madper Xie.

**Comment by agriel** [comment]
Sorry, Madper. I haven't visited this in a long time, so all my knowledge regarding how this work is long gone.

**Comment by madper** [comment]
:-)   thanks for your reply. I'll try to slove it myself.   ;-)

**Comment by agriel** [comment]
I ended up being curious, and decided to revisit this. Give me sometime to figure out how this works, and I'll help if I can. Let me know if you figure it out before I do

**Comment by madper** [comment]
Sure I will. That's very kind of you!!!
